services:
  nginx:
    image: nginx:latest
    container_name: nginx
    user: "2000:2000"
    security_opt:
      - apparmor:unconfined 
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - 80:80
      - 443:443       #for AdguardHome over HTTPS, UI
      - 53:53/tcp     #for AdguardHome
      - 53:53/udp     #for AdguardHome
      - 853:853/tcp   #for AdguardHome over TLS
      - 389:389       #for LDAP
      - 636:636       #for LDAP/S
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/certbot/etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /opt/certbot/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    networks:
      core_net:
        ipv4_address: "172.30.255.10"
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    user: "2700:2700"
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - adguard-work:/opt/adguardhome/work
      - /opt/adguardhome/config:/opt/adguardhome/conf
      - /opt/certbot/etc/letsencrypt/live/adguard.internal:/etc/letsencrypt/live/adguard.internal:ro
      - /opt/certbot/etc/letsencrypt/archive/adguard.internal:/etc/letsencrypt/archive/adguard.internal:ro
    networks:
      core_net:
        ipv4_address: "172.30.255.20"
    environment:
      - TZ=America/New_York

  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    environment:
      - BIND9_USER=bind
      - BIND9_UID=2001
      - BIND9_GID=2001
    ports: 
      - "5353:53/tcp"
      - "5353:53/udp"
    cap_add:
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    volumes:
      - /opt/bind9/config:/etc/bind
      - /opt/bind9/lib:/var/lib/bind:rw
      - bind9-cache:/var/cache/bind
      - /opt/certbot/etc/letsencrypt/live/dns.internal:/etc/letsencrypt/live/dns.internal:ro
      - /opt/certbot/etc/letsencrypt/archive/dns.internal:/etc/letsencrypt/archive/dns.internal:ro
    command: ["-g", "-c", "/etc/bind/named.conf"]
    networks:
      core_net:
        ipv4_address: "172.30.255.30"
    restart: unless-stopped

  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    user: "2002:2002"
    volumes:
      - /opt/step-ca/data:/home/step
      - /opt/step-ca/stepca-entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    restart: "no" # Essential so it doesn't loop while waiting for your signature
    networks:
      core_net:
        ipv4_address: "172.30.255.40"

  # openldap:
  #   image: osixia/openldap:latest
  #   container_name: openldap
  #   user: "2003:2003"
  #   networks:
  #     core_net:
  #       ipv4_address: 172.30.255.50

  certbot:
    image: certbot/dns-rfc2136:latest
    container_name: certbot
    volumes:
      - /opt/cerbot/etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock # Allows container to run docker commands
      - /opt/certbot/hooks:/etc/letsencrypt/renewal-hooks/deploy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      core_net:

volumes:
  adguard-work:
  bind9-cache:

networks:
  core_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.255.0/24"