- hosts: localhost
  become: true
  tasks:
    - name: Edit docker-compose to add memory limit
      ansible.builtin.replace:
        path: /opt/nginx/docker-compose.yml
        regexp: 'limits:.*'
        replace: "limits:\n          memory: 40M"
    - name: Test compose
      ansible.builtin.shell: docker compose -f /opt/nginx/docker-compose.yml config
