---
- name: Section 4 - Environment Cleanup
  hosts: "{{ target_host }}"
  become: true
  vars_files:
    - "{{ playbook_dir }}/../../custom-vars.yaml"
    - "{{ playbook_dir }}/../advanced-vars.yaml"

  pre_tasks:
    - name: Reload resolved vars
      tags: [always]
      ansible.builtin.include_vars:
        file: "{{ deploy_base_dir }}/vars.yaml"


  tasks:
    - name: Section 4 - Environment Cleanup
      tags: [preconditioning, cleanup]
      block:
        - name: Remove existing project containers
          community.docker.docker_container:
            name: "{{ item }}"
            state: absent
          loop: "{{ project_containers }}"
          failed_when: false
