#!/bin/bash
set -euo pipefail

# --- Paths ---
STEPPATH="/home/step"
CONFIG_DIR="$STEPPATH/config"
CONFIG_FILE="$CONFIG_DIR/ca.json"
CERT_DIR="$STEPPATH/certs"
SECRETS_DIR="$STEPPATH/secrets"
ARTIFACTS_DIR="$STEPPATH/artifacts"

# Required files provided by YOU (the host)
ROOT_CERT="$CERT_DIR/root_ca.crt"

# Files generated by THIS script
INTER_KEY="$SECRETS_DIR/intermediate_ca_key"
INTER_CSR="$ARTIFACTS_DIR/intermediate.csr"
INTER_CERT="$CERT_DIR/intermediate_ca.crt"
PASS_FILE="$SECRETS_DIR/password"

mkdir -p "$CERT_DIR" "$SECRETS_DIR" "$ARTIFACTS_DIR" "$CONFIG_DIR"

# --- 1. Pre-Flight Check ---
if [ ! -f "$ROOT_CERT" ]; then
    echo "[!] Error: 'root_ca.crt' not found in $CERT_DIR."
    echo "    Please provide your Root CA public cert before starting."
    exit 1
fi

# --- 2. Initial Bootstrap Logic ---
if [ ! -f "$CONFIG_FILE" ]; then
    echo "[*] No ca.json found. Starting initial bootstrap..."

    if [ ! -f "$INTER_CERT" ]; then
        echo "[*] Generating Intermediate Private Key and CSR..."
        
        # Create a dummy password if it doesn't exist
        if [ ! -f "$PASS_FILE" ]; then
            head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 > "$PASS_FILE"
        fi

        # Generate the Key and CSR
        step certificate create "Internal Intermediate CA" "$INTER_CSR" "$INTER_KEY" \
            --csr --force --no-password --insecure
            
        echo "------------------------------------------------------------"
        echo "[+] SUCCESS: CSR generated at: $INTER_CSR"
        echo "[!] NEXT STEP: Modify this command for appropriate paths and Subject Alternative Names:"
        echo "sudo bash /opt/easyrsa/sign-certs.sh --csr-path /opt/step-ca/data/artifacts/intermediate.csr --san <example.com>"
        echo "------------------------------------------------------------"
        exit 0
    fi

    # If the user has now provided the signed cert, initialize the CA config
    echo "[*] Found signed intermediate. Initializing step-ca config..."
    step ca init --name "Home Network CA" \
        --deployment-type standalone \
        --root "$ROOT_CERT" \
        --key "$INTER_KEY" \
        --crt "$INTER_CERT" \
        --address ":9000" \
        --dns "localhost,step-ca.internal" \
        --password-file "$PASS_FILE" --provisioner "admin"
fi

# --- 3. Production Startup ---
echo "[+] Configuration found. Starting step-ca..."
exec /usr/local/bin/step-ca "$CONFIG_FILE" --password-file "$PASS_FILE"
